### PR TITLE
feat: Amazon Bedrock Support ⛰️

### PR DESCRIPTION
**Pull request by JGalego**
Adds support for [Amazon Bedrock](https://aws.amazon.com/bedrock) models via [Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html).

Tested on the [*A Murder Mistery* 🕵️](https://github.com/google-deepmind/concordia/blob/main/examples/whodunnit.ipynb) scenario with [Mistral Small](https://aws.amazon.com/bedrock/mistral/).

**Changes:**
* Adds `AmazonBedrockLanguageModel` class
* Updates pkg dependencies (+ `boto3`)

PS: Thanks to @jzleibo for presenting this project at [OxML24](https://www.oxfordml.school/replearning).

### CODE REVIEW

**Comment by JGalego** [comment]
CLA signed ✍🏻 PR blocked due to unrelated issues detected by GitHub Actions

**Comment by duenez** [comment]
Maybe this needs to be sync'd to head? I don't see that error in the main branch.

**Comment by duenez** [comment]
Nevermind, I see the problem. Fix is on its way.

**Comment by JGalego** [comment]
> Maybe this needs to be sync'd to head? I don't see that error in the main branch.

Last commit to `main` is 2d old and I forked this today, so that's not an issue. The `install-examples` action is converting the notebooks to python files and the issues are there.

**Comment by duenez** [comment]
This should be fixed at head now.

**Comment by JGalego** [comment]
Missed your initial comment. Thanks for fixing this so fast - branch sync'd, all checks ✅

**Review by duenez — APPROVED** [review]
Looks good, thanks!

**Comment by austinmw** [comment]
@JGalego Hi, curious if it'd make sense to use function calling support in the future in order to remove the need for parsing and retries?

**Comment by JGalego** [comment]
> @JGalego Hi, curious if it'd make sense to use function calling support (for available models) in the future in order to remove the need for parsing and retries (`_MAX_MULTIPLE_CHOICE_ATTEMPTS`)?

IMHO for the retry mechanism, it would be overkill. Also, the goal was to keep the implementation consistent (similar) to the other LM providers. Having said that, `tool use` is listed as an improvement in the [original paper](https://arxiv.org/pdf/2312.03664) (hence why I went for the Converse API).

Screenshot 2024-07-13 at 08 21 15

**Comment by JGalego** [comment]
@duenez The `feedback/copybara` check is failing - anything I should do?

**Comment by jzleibo** [comment]
Earlier today I attempted to follow the instructions we have to fix the
minor lint error which was blocking it from submitting. I believe my edit
is now waiting on approval from Edgar or John. Then once they approve it
the whole pull request will go in.

**Pull request merged**
