### PR TITLE
Fix calendar example

### LINKED ISSUE #66: Calendar.ipynb example issues
Hi, I have come across a few issues with the `calendar.ipynb` example that I thought I should report. I'm using commit `77d70f631779f11df150e4b6946dcbc51af48af4` (July 10, 2024).

### 1. Imports

The imports for the custom components are not set correctly with respect to the notebook's path. The examples directory is not in python's path by default, so these will fail to import:

```python
from examples.phone.components import apps
from examples.phone.components import triggering
```

This is easy to fix, but figured I'd mention.

### 2. Hanging in notebook environment

I'm unable to run this notebook in a Jupyter environment to completion, however it does run to completion in script form. It gets through a few steps and then hangs. I suspect there may be a deadlock occurring in the code due to nested usage of ThreadPoolExecutor, but am not quite sure. (I'm currently running on a Macbook Pro and have tried it in basic Jupyter Lab and VSCode Notebooks — I've had a couple others reproduce this issue on their systems).

### 3. Never actually uses calendar app

Even after I convert to script and run to completion, it never actually uses the calendar app. I set break points at [this line](https://github.com/google-deepmind/concordia/blob/d5f93970e774ad50d883bc838926b7047af822c7/examples/phone/components/apps.py#L260) and [this line](https://github.com/google-deepmind/concordia/blob/f1cd7b31bde75b1c2aab8054992335a6a665047a/examples/phone/components/triggering.py#L117), and it runs to the end of 12 episodes without ever hitting either of those. I've run this over a dozen times with gpt-4o to check, and I've also had another person reproduce and confirm this issue on their system.

When I step through with a debugger, it appears that [this line](https://github.com/google-deepmind/concordia/blob/f1cd7b31bde75b1c2aab8054992335a6a665047a/examples/phone/components/triggering.py#L116) never returns, and instead gets stuck in a recursive loop.

### PR DESCRIPTION
**Pull request by austinmw**
Fixes #66 

Some of these changes are definitely bugs preventing intended behavior from working, while others are improvements to the existing code to prevent edge cases I discovered. I separated the changes to `examples/phone` from the other changes in two separate commits in case you'd only like the former.

## `phone/components/scene.py`

- Fix `_PHONE_CALL_TO_ACTION` format variable to `name` instead of `agent_name` (this caused phone episodes to always fail before executing any phone actions)
- Fix `_PHONE_ACTION_SPEC` to use `OutputType.FREE` instead of `'FREE'` (which has no matching condition in `player.act()`)
- Update `did_conclude` chain of thought to be more descriptive (I was seeing it unable to understand that a task was complete and therefore running for the full 20 steps)
- Update `_PHONE_CALL_TO_ACTION` so it considers the most recent observation (I was seeing that if the most recent event was "Alice schedules meeting with Bob using smartphone", this prompt sees that as already done, so picks something else to do instead.) I think this wasn't needed previously because another bug was causing phone triggering events to never be observed?

## `phone/components/apps.py`

- Add `_print` method to `PhoneApp`
- Add `_print` statement to `ToyCalendar.add_meeting`
- Add check for unexpected arguments to `PhoneApp.invoke_action` (to prevent errors in `return getattr(self, action.name)(**args)` if a unexpected arg is provided)
- Update `Phone.description` to: "has *only* the following apps available" (since I was getting events like "Bob uses the Camera app to take photographs", which triggered the phone scene, but then scheduled an irrelevant meeting)
- Add `ToyCalendar.check_calendar` app action (since previously I was seeing that an event like, "Alice uses the Calendar app to check her schedule for the day and confirm her appointment with Bob." could only route to `add_meeting`, so it would repeat adding the same meeting). There's probably a better way to check to see if none of the app actions make sense in the context of the event and do nothing instead.

## `phone/components/triggering.py`

- Make phone triggering `yes_no_question` clearer in `_is_phone_event` and `_get_player_from_event` (I was seeing events like, "Alice sent a message to bob to schedule meeting" not being recognized as a phone action)

## `phone/calendar.ipynb`

- Add project root to python path to fix `examples.phone.components` import issue
- Fix `START_TIME` to be at `SETUP_TIME` instead of one hour after (since Alice's plan typically mentions scheduling the meeting at `SETUP_TIME` [8 AM], but the simulation was starting at 9 AM, so she seemed to think she already did that and no longer needs to)
- Change major clock step size to be 15 minutes instead of 1 hour (since Alice's plan typically involves taking 15 minutes to schedule the meeting, so if step size is much larger than that, she seems to skip this activity and instead choose plans with longer durations [like eating breakfast])
- Add missing `clock_now` to `SimIdentity`
- Remove unused `victim` variable
- Update `utterance_from_user` to be more explicit (since Alice was giving false positive confirmation by confusing plans for events)
- Change `ObservationSummary.timeframe_delta_until` to 15 minutes to match clock step size

**Note:** During the interrogation phase, since after 12 episodes, the `current observations` will not be far enough back in time to recall scheduling the meeting, and the `summary of observations` may skip this detail, Alice may answer that she doesn't recall whether she has successfully scheduled the meeting. Although not ideal, this seems better in my opinion than her just assuming she scheduled it because it's in her `plan`, as was previously happening.

**Reminder:** Need to comment out the pip installs in this notebook to preserve the below changes (the `thought_chains` modification appeared necessary in my testing to prevent edge cases)

## `observation.py`

- in `pre_observe` and `observe`, strip whitespace from observation to improve "[observation]" formatting

## `thought_chains.py`

- Changed `thought_chains.result_to_who_what_where`'s `open_question` from "who the event is about" to "the main person the event is about" (since I was previously seeing outputs like, e.g., "Bob is eating breakfast while Alice is scheduling a meeting", which resulted in triggering a 2nd phone event for Alice, even though Alice had already just scheduled the event and bob is the one currently acting)

### CODE REVIEW

**Comment by austinmw** [comment]
hey, not quite sure about the two failures due to `Name 'get_ipython' is not defined` here

**Comment by jzleibo** [comment]
I suspect that it's just a linter issue blocking this from submitting. I'll try and follow the steps we have on our side to fix the issue now so that this can get merged.

**Comment by jzleibo** [comment]
actually, there seems to be something different going on with this PR. I think the system sees it as having a deeper error, so it's not letting me do the next step in our process to merge it. This will take a bit more investigation I think.. Bear with us us while we figure it out. Sorry for the delay

**Review by jzleibo — APPROVED** [review]

**Comment by jzleibo** [comment]
This is merged now!

**Pull request merged**
